import * as Print from "expo-print";
import { useLocalSearchParams } from "expo-router";
import { doc, getDoc } from "firebase/firestore";
import React, { useEffect, useState } from "react";
import {
    ActivityIndicator,
    Alert,
    ScrollView,
    StyleSheet,
    View,
} from "react-native";
import { Button, Card, Divider, Text } from "react-native-paper";
import { db } from "../../../../lib/firebase";

const PRIMARY_COLOR = "#6200EE";
const BACKGROUND_COLOR = "#FFFFFF";

// ✅ Define order type for safety
type Order = {
  id: string;
  buyerName?: string;
  phone?: string;
  productName?: string;
  quantity?: number;
  price?: number;
  totalPrice?: number;
  address?: string;
  paymentMethod?: string;
  status?: string;
  deliveryNote?: string;
  createdAt?: { seconds: number; nanoseconds?: number };
};

export default function AdminShopInvoiceScreen() {
  // ✅ Strongly type useLocalSearchParams
  const { orderId } = useLocalSearchParams<{ orderId: string }>();

  const [order, setOrder] = useState<Order | null>(null);
  const [loading, setLoading] = useState(true);

  // 🔹 Fetch order from Firestore
  useEffect(() => {
    const fetchOrder = async () => {
      if (!orderId) return;

      try {
        const ref = doc(db, "orders", orderId);
        const snap = await getDoc(ref);
        if (snap.exists()) {
          const data = snap.data() as Omit<Order, "id">;
          setOrder({ id: snap.id, ...data });
        } else {
          Alert.alert("Error", "Order not found.");
        }
      } catch (err) {
        console.error("Error fetching order:", err);
        Alert.alert("Error", "Failed to fetch order details.");
      } finally {
        setLoading(false);
      }
    };

    fetchOrder();
  }, [orderId]);

  // 🔹 Generate PDF
  const generatePDF = async () => {
    if (!order) return;

    const createdDate = order.createdAt?.seconds
      ? new Date(order.createdAt.seconds * 1000).toLocaleString()
      : new Date().toLocaleString();

    const html = `
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; color: #333; }
            h1, h2, h3 { color: ${PRIMARY_COLOR}; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { padding: 10px; border: 1px solid #ddd; text-align: left; }
            .footer { margin-top: 40px; text-align: center; font-size: 13px; color: #666; }
          </style>
        </head>
        <body>
          <h1>EliteHub - Shop Invoice</h1>
          <h3>Invoice ID: ${order.id}</h3>
          <p><strong>Customer:</strong> ${order.buyerName || "N/A"}</p>
          <p><strong>Phone:</strong> ${order.phone || "N/A"}</p>
          <p><strong>Address:</strong> ${order.address || "N/A"}</p>
          <p><strong>Date:</strong> ${createdDate}</p>

          <h2>Order Details</h2>
          <table>
            <tr><th>Product</th><td>${order.productName || "N/A"}</td></tr>
            <tr><th>Quantity</th><td>${order.quantity || 1}</td></tr>
            <tr><th>Price (₦)</th><td>${order.price?.toLocaleString() || "0"}</td></tr>
            <tr><th>Total (₦)</th><td>${order.totalPrice?.toLocaleString() || "0"}</td></tr>
          </table>

          <h2>Payment Summary</h2>
          <p><strong>Payment Method:</strong> ${order.paymentMethod || "Not specified"}</p>
          <p><strong>Status:</strong> ${order.status || "Pending"}</p>

          ${
            order.deliveryNote
              ? `<h3>Delivery Note</h3><p>${order.deliveryNote}</p>`
              : ""
          }

          <div class="footer">
            <p>Generated by EliteHub Admin Dashboard</p>
            <p>© ${new Date().getFullYear()} EliteHub</p>
          </div>
        </body>
      </html>
    `;

    await Print.printAsync({ html });
  };

  // 🔹 Loading UI
  if (loading) {
    return (
      <View style={styles.center}>
        <ActivityIndicator color={PRIMARY_COLOR} size="large" />
      </View>
    );
  }

  // 🔹 No order found
  if (!order) {
    return (
      <View style={styles.center}>
        <Text>No invoice data found.</Text>
      </View>
    );
  }

  // 🔹 Render invoice view
  return (
    <ScrollView style={styles.container}>
      <Card style={styles.card}>
        <Card.Title
          title="Admin Shop Invoice"
          titleStyle={{ color: PRIMARY_COLOR }}
        />
        <Card.Content>
          <Text style={styles.label}>Invoice ID: {order.id}</Text>
          <Text>Customer: {order.buyerName || "N/A"}</Text>
          <Text>Phone: {order.phone || "N/A"}</Text>
          <Text>Product: {order.productName || "N/A"}</Text>
          <Text>Quantity: {order.quantity || 1}</Text>
          <Text>Price: ₦{order.price?.toLocaleString() || "0"}</Text>
          <Divider style={{ marginVertical: 10 }} />
          <Text style={styles.total}>
            Total: ₦{order.totalPrice?.toLocaleString() || "0"}
          </Text>
          <Text>Payment Method: {order.paymentMethod || "N/A"}</Text>
          <Text>Status: {order.status || "Pending"}</Text>
          <Text>Address: {order.address || "N/A"}</Text>
          {order.deliveryNote && <Text>Note: {order.deliveryNote}</Text>}
          <Text>
            Date:{" "}
            {order.createdAt?.seconds
              ? new Date(order.createdAt.seconds * 1000).toLocaleString()
              : "N/A"}
          </Text>
        </Card.Content>
      </Card>

      <View style={{ marginTop: 20 }}>
        <Button
          mode="contained"
          icon="download"
          onPress={generatePDF}
          style={styles.btn}
        >
          Download / Print Invoice
        </Button>

        <Button
          mode="outlined"
          onPress={() =>
            Alert.alert("Admin Info", "Invoice preview only — no edit access.")
          }
          style={{ marginTop: 10 }}
        >
          Close
        </Button>
      </View>
    </ScrollView>
  );
}

// 🔹 Styles
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BACKGROUND_COLOR, padding: 16 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  card: { marginBottom: 16 },
  label: { fontWeight: "bold", marginBottom: 6 },
  total: { fontSize: 18, fontWeight: "bold", color: PRIMARY_COLOR },
  btn: { backgroundColor: PRIMARY_COLOR, marginTop: 10 },
});
