import * as Print from "expo-print";
import { useLocalSearchParams } from "expo-router";
import { doc, getDoc } from "firebase/firestore";
import React, { useEffect, useState } from "react";
import {
    ActivityIndicator,
    Alert,
    ScrollView,
    StyleSheet,
    View,
} from "react-native";
import { Button, Card, Divider, Text } from "react-native-paper";
import { db } from "../../../lib/firebase";

const PRIMARY_COLOR = "#6200EE";
const BACKGROUND_COLOR = "#FFFFFF";

export default function AdminInvoiceScreen() {
  const { orderId } = useLocalSearchParams<{ orderId: string }>();
  const [order, setOrder] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchOrder = async () => {
      try {
        const ref = doc(db, "orders", orderId);
        const snap = await getDoc(ref);
        if (snap.exists()) {
          setOrder({ id: snap.id, ...snap.data() });
        } else {
          Alert.alert("Error", "Order not found.");
        }
      } catch (err) {
        Alert.alert("Error", "Failed to fetch order details.");
      } finally {
        setLoading(false);
      }
    };
    fetchOrder();
  }, [orderId]);

  const generatePDF = async () => {
    if (!order) return;

    const html = `
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; color: #333; }
            h1, h2, h3 { color: ${PRIMARY_COLOR}; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { padding: 10px; border: 1px solid #ddd; text-align: left; }
            .footer { margin-top: 40px; text-align: center; font-size: 13px; color: #666; }
          </style>
        </head>
        <body>
          <h1>CallonDemand - Admin Invoice</h1>
          <h3>Invoice ID: ${order.id}</h3>
          <p><strong>Customer:</strong> ${order.buyerName}</p>
          <p><strong>Address:</strong> ${order.address}</p>
          <p><strong>Phone:</strong> ${order.phone || "N/A"}</p>
          <p><strong>Date:</strong> ${new Date(
            order.createdAt?.seconds * 1000
          ).toLocaleString()}</p>

          <h2>Order Details</h2>
          <table>
            <tr><th>Food</th><td>${order.foodName}</td></tr>
            <tr><th>Portion</th><td>${order.portionCount}</td></tr>
            <tr><th>Proteins</th><td>${
              order.proteins
                ? order.proteins.map((p: any) => `${p.name} x${p.quantity}`).join(", ")
                : "None"
            }</td></tr>
            <tr><th>Soups</th><td>${
              order.soups?.length ? order.soups.join(", ") : "None"
            }</td></tr>
            <tr><th>Extras</th><td>${
              order.extras?.length
                ? order.extras.map((e: any) => e.name).join(", ")
                : "None"
            }</td></tr>
          </table>

          <h2>Payment Summary</h2>
          <p><strong>Total:</strong> ₦${order.totalPrice?.toLocaleString()}</p>
          <p><strong>Payment Method:</strong> ${
            order.paymentMethod || "Not specified"
          }</p>
          <p><strong>Status:</strong> ${order.status}</p>

          ${
            order.deliveryNote
              ? `<h3>Delivery Note</h3><p>${order.deliveryNote}</p>`
              : ""
          }

          <div class="footer">
            <p>Generated by Admin Dashboard</p>
            <p>CallonDemand © ${new Date().getFullYear()}</p>
          </div>
        </body>
      </html>
    `;

    await Print.printAsync({ html });
  };

  if (loading)
    return (
      <View style={styles.center}>
        <ActivityIndicator color={PRIMARY_COLOR} size="large" />
      </View>
    );

  if (!order)
    return (
      <View style={styles.center}>
        <Text>No invoice data found.</Text>
      </View>
    );

  return (
    <ScrollView style={styles.container}>
      <Card style={styles.card}>
        <Card.Title title="Admin Invoice Summary" titleStyle={{ color: PRIMARY_COLOR }} />
        <Card.Content>
          <Text style={styles.label}>Invoice ID: {order.id}</Text>
          <Text>Customer: {order.buyerName}</Text>
          <Text>Phone: {order.phone || "N/A"}</Text>
          <Text>Food: {order.foodName}</Text>
          <Text>Portion(s): {order.portionCount}</Text>
          <Text>
            Proteins:{" "}
            {order.proteins
              ? order.proteins.map((p: any) => `${p.name} x${p.quantity}`).join(", ")
              : "None"}
          </Text>
          <Text>
            Soups: {order.soups?.length ? order.soups.join(", ") : "None"}
          </Text>
          <Text>
            Extras:{" "}
            {order.extras?.length
              ? order.extras.map((e: any) => e.name).join(", ")
              : "None"}
          </Text>
          <Divider style={{ marginVertical: 10 }} />
          <Text style={styles.total}>Total: ₦{order.totalPrice?.toLocaleString()}</Text>
          <Text>Payment Method: {order.paymentMethod || "N/A"}</Text>
          <Text>Status: {order.status}</Text>
          <Text>Address: {order.address}</Text>
          {order.deliveryNote && <Text>Note: {order.deliveryNote}</Text>}
          <Text>
            Date:{" "}
            {order.createdAt?.seconds
              ? new Date(order.createdAt.seconds * 1000).toLocaleString()
              : "N/A"}
          </Text>
        </Card.Content>
      </Card>

      <View style={{ marginTop: 20 }}>
        <Button
          mode="contained"
          icon="download"
          onPress={generatePDF}
          style={styles.btn}
        >
          Download / Print Invoice
        </Button>

        <Button
          mode="outlined"
          onPress={() => Alert.alert("Admin Info", "Invoice preview only")}
          style={{ marginTop: 10 }}
        >
          Close
        </Button>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BACKGROUND_COLOR, padding: 16 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  card: { marginBottom: 16 },
  label: { fontWeight: "bold", marginBottom: 6 },
  total: { fontSize: 18, fontWeight: "bold", color: PRIMARY_COLOR },
  btn: { backgroundColor: PRIMARY_COLOR, marginTop: 10 },
});
