import * as Print from "expo-print";
import { useLocalSearchParams } from "expo-router";
import { doc, getDoc } from "firebase/firestore";
import React, { useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, View } from "react-native";
import { Button, Card, Divider, Text } from "react-native-paper";
import { db } from "../../../../lib/firebase";

const PRIMARY_COLOR = "#6200EE";

export default function AdminInvoiceScreen() {
  const { orderId } = useLocalSearchParams<{orderId:string}>();
  const [order, setOrder] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(()=>{
    const fetchOrder = async ()=>{
      try {
        const snap = await getDoc(doc(db,"logistics_orders",orderId));
        if(snap.exists()) setOrder({id:snap.id,...snap.data()});
        else Alert.alert("Error","Order not found");
      } catch(err){ Alert.alert("Error","Failed to fetch order"); }
      finally{ setLoading(false); }
    };
    fetchOrder();
  },[orderId]);

  const generatePDF = async ()=>{
    if(!order) return;
    const html = `<html><head><style>
      body{font-family:Arial;padding:20px;color:#333;}
      h1,h2{color:${PRIMARY_COLOR};}
      table{width:100%;border-collapse:collapse;margin-top:20px;}
      th,td{padding:10px;border:1px solid #ddd;text-align:left;}
      .footer{margin-top:40px;text-align:center;font-size:13px;color:#666;}
    </style></head>
    <body>
      <h1>Admin Invoice</h1>
      <h3>Invoice ID: ${order.id}</h3>
      <p>Customer: ${order.buyerName}</p>
      <p>Pickup: ${order.pickup}</p>
      <p>Destination: ${order.destination}</p>
      <p>Vehicle: ${order.vehicleType}</p>
      <p>Shipping Type: ${order.shippingType}</p>
      <p>Status: ${order.status}</p>
      <p>Date: ${new Date(order.createdAt?.seconds*1000).toLocaleString()}</p>
      <div class="footer"><p>Generated by Admin Dashboard</p></div>
    </body></html>`;
    await Print.printAsync({html});
  };

  if(loading) return <View style={styles.center}><ActivityIndicator color={PRIMARY_COLOR} size="large" /></View>;
  if(!order) return <View style={styles.center}><Text>No invoice found.</Text></View>;

  return (
    <ScrollView style={styles.container}>
      <Card style={styles.card}>
        <Card.Title title="Admin Invoice" titleStyle={{color:PRIMARY_COLOR}}/>
        <Card.Content>
          <Text>Invoice ID: {order.id}</Text>
          <Text>Customer: {order.buyerName}</Text>
          <Text>Pickup: {order.pickup}</Text>
          <Text>Destination: {order.destination}</Text>
          <Text>Vehicle: {order.vehicleType}</Text>
          <Text>Shipping: {order.shippingType}</Text>
          <Text>Status: {order.status}</Text>
          <Divider style={{marginVertical:10}}/>
        </Card.Content>
      </Card>
      <Button mode="contained" onPress={generatePDF} style={styles.btn}>Download / Print Invoice</Button>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container:{flex:1,padding:16},
  card:{marginBottom:16},
  btn:{marginTop:10,backgroundColor:PRIMARY_COLOR},
  center:{flex:1,justifyContent:"center",alignItems:"center"}
});
